import IconSpa from "../assets/images/avatars/serenity-spa-and-wellness.jpg";
import IconAnalytics from "../assets/images/avatars/elevate-education.jpg";
import IconEcoGame from "../assets/images/avatars/pixel-playground.jpg";
import IconEmmaR from "../assets/images/avatars/emma-richardson.jpg";
import IconDeltaTaxi from "../assets/images/avatars/swift-ride-share.jpg";
import IconShop from "../assets/images/avatars/sun-park.jpg";
import IconsLiam from "../assets/images/avatars/liam-hughes.jpg";

export type TransactionsOBJ = {
    id: string,
    name: string,
    category: string,
    date: string,
    amount: string,
    usd: number,
    icon: string
}

const TransactionsList: TransactionsOBJ[] = [
    {
        id: "1",
        name: "bravo zen spa",
        category: "personal care",
        date: "29 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconSpa,
    },
    {
        id: "2",
        name: "alpha analytics",
        category: "general",
        date: "15 Aug 2024",
        amount: "+$425.00",
        usd: 425,
        icon: IconAnalytics,
    },
    {
        id: "3",
        name: "echo game store",
        category: "entertainment",
        date: "22 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconEcoGame,

    },
    {
        id: "4",
        name: "emma richardson",
        category: "personal care",
        date: "20 Aug 2024",
        amount: "-$21.50",
        usd: 21.50,
        icon: IconEmmaR
    },
    {
        id: "5",
        name: "delta taxi",
        category: "transportation",
        date: "18 Aug 2024",
        amount: "-$15.00",
        usd: 15,
        icon: IconDeltaTaxi
    },
    {
        id: "6",
        name: "online shop",
        category: "general",
        date: "15 Aug 2024",
        amount: "-$15.00",
        usd: 15,
        icon: IconShop
    },
    {
        id: "7",
        name: "bravo zen spa",
        category: "personal care",
        date: "13 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconSpa,
    },
    {
        id: "8",
        name: "liam hughes",
        category: "general",
        date: "05 Aug 2024",
        amount: "-$250.00",
        usd: 250,
        icon: IconsLiam,
    },
    {
        id: "9",
        name: "alpha analytics",
        category: "general",
        date: "27 Aug 2024",
        amount: "+$1425.00",
        usd: 1425,
        icon: IconAnalytics,
    },
    {
        id: "10",
        name: "electronics LCC",
        category: "bills",
        date: "01 Aug 2024",
        amount: "-$150.00",
        usd: 150,
        icon: IconAnalytics,
    },
    {
        id: "11",
        name: "bravo zen spa",
        category: "personal care",
        date: "08 Jun 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconSpa,
    },
    {
        id: "12",
        name: "alpha analytics",
        category: "general",
        date: "08 Jul 2024",
        amount: "+$425.00",
        usd: 425,
        icon: IconAnalytics,
    },
    {
        id: "13",
        name: "echo game store",
        category: "lifestyle",
        date: "03 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconEcoGame,

    },
    {
        id: "14",
        name: "emma richardson",
        category: "personal care",
        date: "10 Aug 2024",
        amount: "-$21.50",
        usd: 21.50,
        icon: IconEmmaR
    },
    {
        id: "15",
        name: "delta taxi",
        category: "transportation",
        date: "19 Feb 2024",
        amount: "-$15.00",
        usd: 15,
        icon: IconDeltaTaxi
    },
    {
        id: "16",
        name: "online shop",
        category: "general",
        date: "16 Aug 2024",
        amount: "-$15.00",
        usd: 15,
        icon: IconShop
    },
    {
        id: "17",
        name: "bravo zen spa",
        category: "personal care",
        date: "13 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconSpa,
    },
    {
        id: "18",
        name: "liam hughes",
        category: "general",
        date: "05 Aug 2024",
        amount: "-$250.00",
        usd: 250,
        icon: IconsLiam,
    },
    {
        id: "19",
        name: "alpha analytics",
        category: "general",
        date: "05 May 2024",
        amount: "+$1425.00",
        usd: 1425,
        icon: IconAnalytics,
    },
    {
        id: "20",
        name: "electronics LCC",
        category: "bills",
        date: "10 Aug 2024",
        amount: "-$150.00",
        usd: 150,
        icon: IconAnalytics,
    },
    {
        id: "21",
        name: "electronics LCC",
        category: "bills",
        date: "19 Nov 2024",
        amount: "-$150.00",
        usd: 150,
        icon: IconAnalytics,
    },
    {
        id: "22",
        name: "bravo zen spa",
        category: "personal care",
        date: "29 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconSpa,
    },
    {
        id: "23",
        name: "alpha analytics",
        category: "general",
        date: "25 Sep 2024",
        amount: "+$ 425.00",
        usd: 425,
        icon: IconAnalytics,
    },
    {
        id: "24",
        name: "echo game store",
        category: "lifestyle",
        date: "22 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconEcoGame,

    },
    {
        id: "25",
        name: "emma richardson",
        category: "personal care",
        date: "05 Sep 2024",
        amount: "-$21.50",
        usd: 21.50,
        icon: IconEmmaR
    },
    {
        id: "26",
        name: "delta taxi",
        category: "transportation",
        date: "19 Aug 2024",
        amount: "-$15.00",
        usd: 15,
        icon: IconDeltaTaxi
    },
    {
        id: "27",
        name: "online shop",
        category: "general",
        date: "15 Aug 2024",
        amount: "-$15.00",
        usd: 15,
        icon: IconShop
    },
    {
        id: "28",
        name: "bravo zen spa",
        category: "personal care",
        date: "13 Aug 2024",
        amount: "-$25.00",
        usd: 25,
        icon: IconSpa,
    },
    {
        id: "29",
        name: "liam hughes",
        category: "general",
        date: "05 Aug 2024",
        amount: "-$250.00",
        usd: 250,
        icon: IconsLiam,
    },
    {
        id: "30",
        name: "alpha analytics",
        category: "general",
        date: "05 Jan 2024",
        amount: "+$1425.00",
        usd: 1425,
        icon: IconAnalytics,
    },
    {
        id: "31",
        name: "electronics LCC",
        category: "bills",
        date: "2 May 2024",
        amount: "-$150.00",
        usd: 150,
        icon: IconAnalytics,
    },
    {
        id: "32",
        name: "electronics LCC",
        category: "bills",
        date: "05 Oct 2024",
        amount: "-$550.00",
        usd: 550,
        icon: IconAnalytics,
    },
];

export default TransactionsList;